### ISSUE TITLE
Request for new release 

### ISSUE THREAD

**Issue by jpsalvesen** [perl5-utils/Hash-Merge#6]
Hi,

This is a gentle reminder that there is desirable, merged code in the master that hasn't been made available as a release. 

In particular this one:

https://github.com/perl5-utils/Hash-Merge/commit/c01a97cdb9930ca81a276d3e6c216f05d6adac08

Best regards,
Jens-Petter Salvesen

**Comment by rehsack** [comment]
Please mind that we might know about issues you don't and we're still working on them.
