### ISSUE TITLE
Recent Version Cannot Merge Hash with Blessed Object

### ISSUE THREAD

**Issue by theory** [perl5-utils/Hash-Merge#7]
theory/sqitch#365 reported an error I hadn't seen before. After upgrading all my CPAN modules and doing some debugging, I determined that Hash::Merge no longer likes to merge hashes that contain blessed hashes. This used to work, but no longer does:

    use Hash::Merge;
    my $h1 = { foo => bless {one => 2}, __PACKAGE__ };
    my $h2 = { foo => bless {one => 2}, __PACKAGE__ };
    my $merged = Hash::Merge->new->merge($h1, $h2);

Output:

    Arguments for _merge_hashes must be hash references at try line 11.

I can see why it might not want to merge objects anymore, even if they're underlying storage is a hash, but there ought to be some way to tweak it. For example, perhaps one could tell Hash::Merge to treat blessed objects as regular scalars and just follow precedence for the entire object?

**Comment by sh85** [comment]
Hello David,
this was not planned. Hash::Merge should be able to merge Hashes even with blessed objects in it.

I've just uploaded Hash::Merge version 0.299 to CPAN.

The new version should fix your issue and work with objects just like the older versions did.
We also included your example as a test and added some tests with blessed objects.

Best regards,
Stefan

**Comment by theory** [comment]
Thanks @sh85 .
